version: '3'

services:
  database-test:
    container_name: postgres-test-1
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: project-manager-api_db
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: project-manager-api_db
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
